---
# This workflow will run periodically to check for new releases of prometheus
# and create pr to update the version when available

name: Update

on:
  schedule:
    - cron: '23 7 * * *'
  workflow_dispatch:
jobs:
  prometheus:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Version of Prometheus
        run: ./version_updater.sh ./prometheus/VERSION https://api.github.com/repos/prometheus/prometheus/releases/latest

      - uses: crazy-max/ghaction-import-gpg@v4.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: Bump Prometheus version from ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }}
          body: '[Prometheus ${{env.LATEST_VERSION}} release](${{env.HTML_URL}})'
          commit-message: Bump Prometheus version to ${{ env.LATEST_VERSION }}
          committer: idva-bot <idva@gsa.gov>
          author: idva-bot <idva@gsa.gov>
          branch: bump-prometheus-version
          reviewers: |
            18f/idva-partners

  alertmanager:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Version of Alertmanager
        run: ./version_updater.sh ./alertmanager/VERSION https://api.github.com/repos/prometheus/alertmanager/releases/latest

      - uses: crazy-max/ghaction-import-gpg@v4.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: Bump Alertmanager version from ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }}
          body: '[Alertmanager ${{env.LATEST_VERSION}} release](${{env.HTML_URL}})'
          commit-message: Bump Alertmanager version to ${{ env.LATEST_VERSION }}
          committer: idva-bot <idva@gsa.gov>
          author: idva-bot <idva@gsa.gov>
          branch: bump-alertmanager-version
          reviewers: |
            18f/idva-partners

  cortex:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Version of Cortex
        run: ./version_updater.sh ./cortex/VERSION https://api.github.com/repos/cortexproject/cortex/releases/latest

      - uses: crazy-max/ghaction-import-gpg@v4.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: Bump Cortex version from ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }}
          body: '[Cortex ${{env.LATEST_VERSION}} release](${{env.HTML_URL}})'
          commit-message: Bump Cortex version to ${{ env.LATEST_VERSION }}
          committer: idva-bot <idva@gsa.gov>
          author: idva-bot <idva@gsa.gov>
          branch: bump-cortex-version
          reviewers: |
            18f/idva-partners

  grafana:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Version of Grafana
        run: ./version_updater.sh ./grafana/VERSION https://api.github.com/repos/grafana/grafana/releases/latest

      - uses: crazy-max/ghaction-import-gpg@v4.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: Bump Grafana version from ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }}
          body: '[Grafana ${{env.LATEST_VERSION}} release](${{env.HTML_URL}})'
          commit-message: Bump Grafana version to ${{ env.LATEST_VERSION }}
          committer: idva-bot <idva@gsa.gov>
          author: idva-bot <idva@gsa.gov>
          branch: bump-grafana-version
          reviewers: |
            18f/idva-partners

  watchtower:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Version of Watchtower
        run: ./version_updater.sh ./watchtower/VERSION https://api.github.com/repos/18F/watchtower/releases/latest

      - uses: crazy-max/ghaction-import-gpg@v4.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: Bump Watchtower version from ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }}
          body: '[Watchtower ${{env.LATEST_VERSION}} release](${{env.HTML_URL}})'
          commit-message: Bump Watchtower version to ${{ env.LATEST_VERSION }}
          committer: idva-bot <idva@gsa.gov>
          branch: bump-watchtower-version
          reviewers: |
            18f/idva-partners
